[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[edge_functions]]
  function = "config"
  path = "/config.js"

[[edge_functions]]
  function = "supabase-config"
  path = "/supabase-config.js"

[[edge_functions]]
  function = "onesignal-config"
  path = "/onesignal-config.js"

[[edge_functions]]
  function = "send-notification"
  path = "/send-notification"

[[edge_functions]]
  function = "record-reaction"
  path = "/record-reaction"

[[edge_functions]]
  function = "save-username"
  path = "/save-username"
