apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'

android {
    namespace 'io.github.jaysolo828_jpg.twa'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.jaysolo828_jpg.twa'
        minSdk 21
        targetSdk 35
        versionCode 20
        versionName '1.0.1.1'
    }

    signingConfigs {
        release {
            storeFile file(System.getenv('KEYSTORE_PATH') ?: 'keystore.jks')
            storePassword System.getenv('KEYSTORE_PASSWORD')
            keyAlias 'my-key-alias'
            keyPassword System.getenv('KEYSTORE_PASSWORD')
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
    implementation 'com.android.billingclient:billing:6.1.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.22'
    implementation platform('com.google.firebase:firebase-bom:33.1.0')
    implementation 'com.google.firebase:firebase-messaging-ktx'
}
